import TextPage from "@/components/TextPage";
import { SITE_NAME } from "@/lib/site";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "About", description: `About ${SITE_NAME}: daily horoscopes, the Chinese zodiac, Khmer traditions and lucky days, written from real sky data.`, path: "/about" });

export default function About() {
  return (
    <TextPage title="About" path="/about">
      <p>{SITE_NAME} is a calm, daily almanac for the modern reader. It brings together Western astrology, the Chinese zodiac, Khmer traditions and the traditional almanac in one place. You choose which traditions you see.</p>
      <h2>How readings are made</h2>
      <p>Every daily reading starts with the real sky. We calculate where the Moon and planets are each day using open astronomy software, then match that to a library of hand-written passages. Nothing is generated by AI, and nothing is made up for decoration. Each reading shows the sky it was built from.</p>
      <p>The Chinese almanac pages use the traditional calendar&apos;s own records of good and challenging days. The Khmer calendar uses the Chhankitek method that printed Khmer calendars follow.</p>
      <h2>What we won&apos;t do</h2>
      <p>No subscriptions to cancel, no fear-based notifications, no paid psychic chats, and no readings about illness, accidents or misfortune.</p>
      <h2>Who it&apos;s for</h2>
      <p>Anyone who enjoys a moment of reflection with their morning coffee. We are based in Cambodia, which is why the Khmer calendar and New Year angel are here.</p>
      <h2>A note on what this is</h2>
      <p>Astrology and almanacs are traditions to enjoy and think with. They are not medical, legal or financial advice, and they can&apos;t tell you what will happen.</p>
    </TextPage>
  );
}
